In [3]:
import numpy as np

In [4]:
np .__version__


'1.20.1'

In [5]:
n = np.array([1,2,3,4,5,6])

In [6]:
n

array([1, 2, 3, 4, 5, 6])

In [7]:
print(n)

[1 2 3 4 5 6]


In [9]:
n.ndim # dimension of array 'n'

1

In [10]:
n.size #size of array


6

In [11]:
n.shape # no of elements in each dimension

(6,)

In [13]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [15]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
a.ndim


2

In [17]:
a.size


12

In [18]:
a.shape

(3, 4)

In [19]:
z = np.array([
    [[1,2,3,4],[5,6,7,8],[9,10,11,12]],
    [[1,2,3,4],[5,6,7,8],[9,10,11,12]],
    [[1,2,3,4],[5,6,7,8],[9,10,11,12]],
])

In [20]:
print(z)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [21]:
z.size


36

In [22]:
z.ndim


3

In [23]:
z.shape

(3, 3, 4)