Slicing


In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [5]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [6]:
a


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [7]:
a[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [8]:
a[:,0:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [9]:
a[0:2,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
a[1:2,:]


array([[ 6,  7,  8,  9, 10]])

In [11]:
a[1:,:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])